# -*- coding: utf-8 -*-
"""lab4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZh5aN48N_OD802kby8bnpN67s5KyLpP
"""

#task1
variable = input("Enter number: " )
print(variable[-1::-1])

#task2
number = input("Please enter a number: ")
number2 = int(input("please enter a number: "))

for i in range(number2,-1,-1):
  print(number[i],end="")
print(number[number2+1:])

#task3
binary = input("Please enter a binary number: ")

for ch in binary:
    if ch != '1' and ch != '0':
        print('Not a Binary Number')
        break
else:
    print('Binary Number')

#task4
number=input("Please enter : ")
if number.endswith('er'):
  number1 = number.replace("er","est")
  print(number1)
elif number.endswith('est'):
  print(number)
else:
    if len(number)<4:
      print(number)
    elif len(number)>3:
      print(number+"er")

#task5
number = input("Please enter a string: ")
length = len(number)
for row in range(length):
  for col in range(row+1):
    print(number[col],end="")

  print()

#task6
value = input("Please enter a string: ")
for ch in value :
  character = ord(ch)
  print(f"{ch} : {character}")

#task7
variable = input("Please enter a string: ")
new_variable = ""
for ch in variable:
  ascii = ord(ch)
  if ascii==ord("z"):
    new_variable = new_variable +"a"
  else:
    new_variable =new_variable +chr(ascii+1)
print(new_variable)

#task8
a = input("please enter a string: ")
l =0
for i in variable :
  if l%2==0:
    i = ""
  else:
    i = ord(i) - 32
    print(chr(i),end="")
  l+=1

#task9
variable = input("Please enter: ")
last = ""
for char in variable :
  if char!= last:
    last = char
  elif char==last:
    last=""
  print(last,end="")
  last =char

#task10
word = input("Please enter: ")
length = 0
count = 0
ok = 0
for char in word:
  length+=1

for char in word:
  if char == ",":
    break
  count+=1

left = str(word[:count:])
right = str(word[count+1::])

for index in range(length):
  print(str(left[ok:ok+1:])+str(right[ok:ok+1:]),end="")
  ok+=1

var1 = input()
var2 = input()
if var2 in var1:
  for ch in range(len(var1))
  elif

n = int(input("Enter the value of 'n': "))
a = 0
b = 1
sum = 0
count = 1
print("Fibonacci Series: ", end = " ")
while(count <= n):
  print(sum, end = " ")
  count += 1
  a = b
  b = sum
  sum = a + b