# -*- coding: utf-8 -*-
"""lab5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JMWuoMmMWuXUQW4LoRY_lTka-nbJthun
"""

#lab mid question
var1 = input("Please enter a string: ")
var2 = input("Please enter a string: ")
length = len(var1)
length2 = len(var2)
i = 0
r=0
while r<length:
  var = var1[r:length2:1]
  if var2==var :
    i+=1
  r+=1
  length2+=1
print(i)

#task1
var1 = [None]*5
ch = 0
while ch<5:
  var = input()
  var1[ch] = var
  print(var1[:ch+1])
  ch+=1

#task2
lst = []
tem = ""
var = list(input())
for i in var:
  if i==",":
    lst.append(int(tem))
    tem=""
  elif i !=" ":
    tem+=i
lst.append(tem)
if len(lst)>3:
  print(lst[2:len(lst)-2])
else:
  print("Not possible")

lst = [5,3,2,8,4]

for i in lst:

lst = [5,3,2,8,4]
max = lst[0]
min = lst[0]
for i in lst:
  if i>max:
    max=i

for i in lst:
  if i<min:
    min=i
print(f"maximum: {max}")
print(f"maximum: {min}")

#task3
last = [None]*5
i=0
while i<len(last):
  var =int(input())
  last[i]=var

  i+=1
i = len(last)-1
while i>=0:
  print(last[i])
  i-=1

#task4
lst = [3, 5, 1, 6]
user =[]
for i in lst :
  var = i**2
  user.append(var)
print(user)

#task5
lst = ["hey", "there", "", "what's", "", "up", "", "?"]
new = []
print("Original List:",lst)
for i in lst:
  if i!="":
    new.append(i)


print("Modified List:",new)

#task6
var1 = input()
var = var1.split(",")
print(var)
for ch in range(len(var)):
  var[ch]=int(var[ch])
print(var)
max = var[0]
max_index = 0
for i in range(len(var)):
  if var[i]>max:
    max = var[i]
    max_index=i
print("Largest number in the list is:",max,"which was found at index:",max_index)

#task7
lst1 = [1, 4, 7, 5]
lst2 = [6, 1, 3, 9]
lst1 =lst1[0:len(lst1)-1:1]+lst2
print(lst1)

#task8
list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two = [10, 11, 12, -13, -14, -15, -16]
s = list_one + list_two
my_list =[]
for i in s:
  if i%2==0:
    my_list.append(i)
print(my_list)

list_one = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list_two = [10, 11, 12, -13, -14, -15, -16]
s = list_one + list_two
print(s)

#task9
#7 12 4 55 96 2 11 61 33 42
var1 =list(input())
my_list =[]
var = ""
for ch in var1 :
  if ch==" ":
    my_list.append(var)
    var=""
  else:
    var+=ch
my_list.append(int(var))

new = []
for ch in my_list:
    if ch%2!=0:
      new.append(ch)
    else:
      pass

print("Original list:",my_list)
print("Modified list:",new)

num = input("Enter numbers: ")
mylist = []
x = ''
for i in num:
    if i != ' ':
        x += i
    else:
        mylist.append(int(x))
        x = ''
mylist.append(int(x))
lst = []
for i in mylist:
    if i % 2 != 0:
        lst.append(i)
    else:
        pass
print("Original list:",mylist)
print("Modified list:",lst)

#task10
my_list = input().split(",")
list1=[]

for ch in range(len(my_list)):
  my_list[ch] =int(my_list[ch])
print("Input list:",my_list)
for i in my_list:
  if i not in list1:
      list1.append(i)
  else:
    pass
print("Modified list:",list1)

#task11
list_one = [1, 4, 3, 2, 6]
list_two = [5, 6, 9, 8, 7]
Flag = False
for i in list_one:
  for j in list_two:
    if i==j:
      Flag=True
  if Flag:
    break
print(Flag)

#random task from previous quiz 3
q

myList1=[1,7,5,8,7]
var1=2
var3=myList1
while (var1<5):
  var2=1
  while(var2<=var1):
    print(myList1[var2])
    var3[var2]=myList1[var2]-var3[var1]-3
    var2= var2+1
  var1=var1+1
print(len(var3)in myList1)

