# -*- coding: utf-8 -*-
"""lab-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDCA7e0wGeOxUna47Xjw9-_fJeirRCQ1
"""

#task 1
print("hello world")

#task 2
print(54+56)

#task 3
season="Fall"
year = 2022
print(season)
print(year)

#task 4
name = input("Please enter your name :")
print("Your name is "+name)

#task 5
m= int(input("Please enter a number: "))
n= int(input("Please enter a number: "))
power= m**n
print(str(m)+"^"+str(n)+":",power)

#task 6
total= int(input("Please enter a number: "))
sum= total//4
max= sum*4
print(max)

#task 7
A=int(input("Please enter a number: "))
B=int(input("Please enter a number: "))
C=int(input("Please enter a number: "))
D=float(input("Please enter a number: "))
result=A**C+B*A-D/3
print(int(result))

#task 8
total = int(input("Please enter a number: "))
each = total//3
result= total%3
print ("Each friend will receive",each,"chocolates")
print("The number of remaining chocolates is",result)

#task 9
first = input("please enter: ")
second = input("please enter: ")
add= second+first
print(add)

#task 10
a=input('please enter: ')
print(a[0])

#task11
var = int(input("Please enter a number: "))
if var is var%2:
  print("False")
else:
  print('True')

