# -*- coding: utf-8 -*-
"""lB6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vIEXu4IUCI9cBKlua2T-ZVcaSKqPkqln
"""

#task1
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print("Output:",a_tuple[3][3])
#if we want to access something from a nestes tuple then we can [][]

#task2
tpl = (10, 20, 24, 25, 26, 35, 70)
print(tpl[2:-2])

#task3
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
index = len(book_info)
print("Size of the tuple is:",index)
for i in book_info:
  print(i)

#task4
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
for i in book_info:
  a,b,c = i
  print(f"{b} won the '{a}' category with {c} votes")

#task5
tpl = (10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
var = int(input())
count = 0
for i in tpl:
  if i==var :
    count+=1
print(f"{var} appears {count} times in the tuple")

#task6
tpl= ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
my_list = []
for i in range(len(tpl)-1,-1,-1):
  my_list.append(tpl[i])
print(tuple(my_list))

#task7
var1 = {'Harry':15, 'Draco':8, 'Nevil':19}
var2 = {'Ginie':18, 'Luna': 14}
dic = {}
dic.update(var1)
dic.update(var2)
print(dic)

#task7
var1 = {'Harry':15, 'Draco':8, 'Nevil':19}
var2 = {'Ginie':18, 'Luna': 14}
dic = {}
for k in var1:
  dic[k] = var1[k]
for k in var2:
  dic[k] = var2[k]
print(dic)

#task8
var =input()
var1 = var.split(",")
for pair in var1:
  k,v = pair.split(":")
  k = k.strip()
  v = int(v)

#task8
var =input()
var1 = var.split(", ")
count = 0
avg = 0
for pair in var1:
  k,v = pair.split(":")
  v = int(v)
  count+=1
  avg+=int(v)
print(f"Average is {int(avg/count)}.")

#task9
var = int(input())
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200
              , 'Kierra Gentry': 165, 'Pierre Cox': 190}
#lst = list(exam_marks.keys())
dic = {}
for i,j in exam_marks.items():
  if j>=var:
    dic[i]=j
print(dic)

#task9
var = int(input())
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200
              , 'Kierra Gentry': 165, 'Pierre Cox': 190}
dic = {}
for i in exam_marks.keys():
  if exam_marks[i]>=var:
    dic[i]=exam_marks[i]
print(dic)

#task10
dict1 = {'sci fi': 12, 'mystery': 15, 'horror': 8, 'mythology': 10, 'young_adult': 4, 'adventure':14}
c = list(dict1.values())
d = list(dict1.keys())
nmax =-9999
count=0
for i in c:
  count+=1
  if i>nmax:
    nmax=i
    count1=count-1
print(f"The highest selling book genre is '{d[count1]}' and the number of books sold are {nmax}.")

#task11
var =input().lower().split(' ')
dic = {}
for i in var:
  for j in i:
    if j in dic:
      dic[j]+=1
    else:
      dic[j]=1
print(dic)

#task12
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
count=0
for i in dict_1:
  for j in dict_1[i]:
    count+=1
print(count)

#task13
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
#need unpacking
dict1 = {}
for i in list_1:
  k, v =i
  if k not in dict1:
    dict1[k] = []
    dict1[k].append(v)
  elif k in dict1:
    dict1[k].append(v)
print(dict1)

#task15
var1 = [(2, 3), (4, 5), (6, 7), (2, 8)]
for i in var1:
  print(i)